### ISSUE TITLE
upgrade to 20160317 fails

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdcadm#16]
I am currently trying to upgrade to 20160317 using the this [procedure](https://github.com/joyent/sdcadm/blob/master/docs/update.md).

Unfortunately, I am stuck after running `sdcadm up -y --all --force-data-path`
All the zones seem to get update without issues but not sapi:
```
--- Updating sapi ...                                                                                                                           
Get SAPI current mode                                                  
Updating image for SAPI service "sapi"                                 
    service uuid: 79819e76-d010-4105-8fe5-c376d2ac4518                 
Installing image a64d684e-ebe1-11e5-a6fe-ef55246939be                  
    (sapi@release-20160317-20160317T013705Z-g7fbf8d7)                  
Updating 'sapi-url' in SAPI                                            
Updating 'sapi-url' in VM 4fbd6bff-aa71-4de9-aae5-c1a6090c4d90         
Verifying if we are on an HA setup                                     
Provisioning Temporary sapi VM sapi0tmp                                
Update error: {"message":"socket hang up","statusCode":500,"body":{"code":"ProvisionFailedError","message":"socket hang up"},"restCode":"Provisi
onFailedError","name":"ProvisionFailedError"}
sdcadm up: error: socket hang up            
```
After that trying to re-run the command just gives me:
```
sdcadm up -y --all --force-data-path          
Finding candidate update images for 23 services (sapi, moray, ufds, imgapi, sdc,
papi, napi, workflow, ca, amonredis, fwapi, adminui, vmapi, manta, redis, amon, dhcpd,
cnapi, cloudapi, mahi, binder, manatee, assets).                       
Using channel release                                                  
sdcadm up: error: do not support the following changes:                
    {"type":"update-service","service":"sapi","image":"a64d684e-ebe1-11e5-a6fe-ef55246939be"}
```

**Comment by trentm** [comment]
@benjamin-bergia I might need to feel this out a bit. Do you have 'sapi0' and 'sapi0tmp' zones on your headnode now? E.g. what is the output of `vmadm list | grep sapi` from your headnode GZ?

If so, then I'm curious if (a) SAPI is working and (b) if that sapi0tmp instance is in SAPI's database. Run the following to find out: `sdc-sapi /instances/$(vmadm lookup -1 alias=sapi0tmp)`

If so, then I think you might be able to back to a working state by destroying that 'sapi0tmp' zone. Try this:

```
sdc-sapi /instances/$(vmadm lookup -1 alias=sapi0tmp) -X DELETE
sdcadm up sapi
```

**Comment by benjamin-bergia** [comment]
@trentm I do have 2 sapi zones now:
```
4fbd6bff-aa71-4de9-aae5-c1a6090c4d90  OS    512      running           sapi0
d7f1011e-8d4f-487c-9091-b30316d6fbca  OS    512      running           sapi0tmp
```
This is the output of the healthcheck
```
ZONE                                 STATE           AGENT               STATUS
global                               running         -                   online
assets                               running         -                   online
sapi                                 running         -                   online
binder                               running         -                   online
manatee                              running         -                   online
moray                                running         -                   online
amonredis                            running         -                   online
redis                                running         -                   online
ufds                                 running         -                   online
workflow                             running         -                   online
amon                                 running         -                   online
sdc                                  running         -                   online
papi                                 running         -                   online
napi                                 running         -                   online
rabbitmq                             running         -                   online
imgapi                               running         -                   online
cnapi                                running         -                   online
dhcpd                                running         -                   online
fwapi                                running         -                   online
vmapi                                running         -                   online
ca                                   running         -                   online
mahi                                 running         -                   online
adminui                              running         -                   online
cloudapi                             running         -                   online
sapi                                 running         -                  svc-err
global                               running         ur                  online
global                               running         smartlogin          online
```

```
sdc-sapi /instances/$(vmadm lookup -1 alias=sapi0tmp)

HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 94
Date: Tue, 29 Mar 2016 01:51:15 GMT
Connection: keep-alive

{
  "code": "ResourceNotFound",
  "message": "no such instance: d7f1011e-8d4f-487c-9091-b30316d6fbca"
}
```

Anyway to remove the temporary instance or to rollback the upgrade ?

**Comment by benjamin-bergia** [comment]
Since the sapi0tmp doesn't appear to be used can I delete it using `vmadm` ? 
I tried to stop it but even after stopping it, I still get the same error. 

My adminui is also not usable despite being listed as 'online'. Any way to quickly rollback the upgrade, this is my production headnode.

**Comment by benjamin-bergia** [comment]
I manually deleted the `sapi0tmp` zone and re-ran `sdcadm up -y --all --force-data-path`. The sapi upgrade went well unfortunately I get a new error on manatee
```
--- Updating manatee ...
Verifying manatee target version
Target version is new enough to avoid setting SAPI back to proto mode
Verifying manatee current version
manatee-adm version is >= 2.1.0. Using new commands
Updating image for SAPI service "manatee"
    service uuid: 04d6fc92-534b-4e2b-a29a-f9d7e722fb47
get local manatee
Getting shard state from local manatee
Getting Server Information for manatee VMs
Getting SDC's moray vms from VMAPI
Getting SDC's workflow vms from VMAPI
Installing image d8c747ca-ebde-11e5-aca6-bf9f0954e211
    (sdc-postgres@release-20160317-20160317T011926Z-g8e996f2)
Update error: {"message":"error importing VM image d8c747ca-ebde-11e5-aca6-bf9f0954e211:\n\targv: [\"/usr/sbin/imgadm\",\"import\",\"-q\",\"d8c747ca-ebde-11e5-aca6-bf9f0954e211\"]\n\texit status: 1\n\tstdout:\n\n\tstderr:\n{\"name\":\"imgadm\",\"req_id\":\"8a2d295b-b645-40fc-aeed-914f6b0998a0\",\"hostname\":\"headnode\",\"pid\":1283,\"level\":20,\"opts\":{},\"args\":[\"import\",\"-q\",\"d8c747ca-ebde-11e5-aca6-bf9f0954e211\"],\"cli\":true,\"msg\":\"cli init\",\"time\":\"2016-03-29T10:17:18.561Z\",\"v\":0}\n{\"name\":\"imgadm\",\"req_id\":\"8a2d295b-b645-40fc-aeed-914f6b0998a0\",\"hostname\":\"headnode\",\"pid\":1283,\"level\":30,\"uuid\":\"d8c747ca-ebde-11e5-aca6-bf9f0954e211\",\"arg\":\"d8c747ca-ebde-11e5-aca6-bf9f0954e211\",\"msg\":\"image-id validated\",\"time\":\"2016-03-29T10:17:18.569Z\",\"v\":0}\n{\"name\":\"imgadm\",\"req_id\":\"8a2d295b-b645-40fc-aeed-914f6b0998a0\",\"hostname\":\"headnode\",\"pid\":1283,\"level\":20,\"subcmd\":\"import\",\"exitStatus\":1,\"cli\":true,\"msg\":\"cli exit\",\"time\":\"2016-03-29T10:17:39.780Z\",\"v\":0}\nimgadm import: error (ECONNRESET): Error: tunneling socket could not be established, statusCode=504\n    at ClientRequest.onConnect (/usr/img/node_modules/restify/node_modules/tunnel-agent/index.js:163:19)\n    at ClientRequest.g (events.js:180:16)\n    at ClientRequest.EventEmitter.emit (events.js:106:17)\n    at Socket.socketOnData (http.js:1612:11)\n    at TCP.onread (net.js:530:27)","we_cause":{"killed":false,"code":1,"signal":null},"code":"InternalError","exitStatus":1}
sdcadm up: error: error importing VM image d8c747ca-ebde-11e5-aca6-bf9f0954e211:
	argv: ["/usr/sbin/imgadm","import","-q","d8c747ca-ebde-11e5-aca6-bf9f0954e211"]
	exit status: 1
	stdout:

	stderr:
{"name":"imgadm","req_id":"8a2d295b-b645-40fc-aeed-914f6b0998a0","hostname":"headnode","pid":1283,"level":20,"opts":{},"args":["import","-q","d8c747ca-ebde-11e5-aca6-bf9f0954e211"],"cli":true,"msg":"cli init","time":"2016-03-29T10:17:18.561Z","v":0}
{"name":"imgadm","req_id":"8a2d295b-b645-40fc-aeed-914f6b0998a0","hostname":"headnode","pid":1283,"level":30,"uuid":"d8c747ca-ebde-11e5-aca6-bf9f0954e211","arg":"d8c747ca-ebde-11e5-aca6-bf9f0954e211","msg":"image-id validated","time":"2016-03-29T10:17:18.569Z","v":0}
{"name":"imgadm","req_id":"8a2d295b-b645-40fc-aeed-914f6b0998a0","hostname":"headnode","pid":1283,"level":20,"subcmd":"import","exitStatus":1,"cli":true,"msg":"cli exit","time":"2016-03-29T10:17:39.780Z","v":0}
imgadm import: error (ECONNRESET): Error: tunneling socket could not be established, statusCode=504
    at ClientRequest.onConnect (/usr/img/node_modules/restify/node_modules/tunnel-agent/index.js:163:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:106:17)
    at Socket.socketOnData (http.js:1612:11)
    at TCP.onread (net.js:530:27)
```
After checking on https://images.joyent.com/images, this image doesn't seem to exist.

**Comment by trentm** [comment]
@benjamin-bergia Sorry this isn't going well.

Yes, manually deleting sapi0tmp with 'vmadm' was fine.


> After checking on https://images.joyent.com/images, this image doesn't seem to exist. 

The update images will be on updates.joyent.com. That image server also has separate "channels" with separate sets of images.

```
$ updates-imgadm -C '*' get d8c747ca-ebde-11e5-aca6-bf9f0954e211
{
  "v": 2,
  "uuid": "d8c747ca-ebde-11e5-aca6-bf9f0954e211",
  "owner": "00000000-0000-0000-0000-000000000000",
  "name": "sdc-postgres",
  "version": "release-20160317-20160317T011926Z-g8e996f2",
  "state": "active",
  "disabled": false,
  "public": false,
  "published_at": "2016-03-17T01:23:10.792Z",
  "type": "zone-dataset",
  "os": "smartos",
  "files": [
    {
      "sha1": "06883122ad52bedf999f5215dd217edc5705a597",
      "size": 75727460,
      "compression": "gzip"
    }
  ],
  "description": "SDC",
  "requirements": {
    "min_platform": {
      "7.0": "20130506T233003Z"
    },
    "networks": [
      {
        "name": "net0",
        "description": "admin"
      }
    ]
  },
  "origin": "b4bdc598-8939-11e3-bea4-8341f6861379",
  "tags": {
    "smartdc_service": true
  },
  "channels": [
    "staging",
    "release"
  ]
}
```

That image is in the "release" and "staging" channels. I'm guessing your SDC is setup to use the "release" channel. Use `sdcadm channel get` to see.


From this error message: "Error: tunneling socket could not be established"
Are you using an http proxy for external access?  Is there output from `set | grep -i proxy` in your headnode global zone?

Is that image in your DC's IMGAPI? `sdc-imgadm get d8c747ca-ebde-11e5-aca6-bf9f0954e211`

Is your headnode GZ's imgadm configured to use the DC's IMGAPI? `imgadm sources -v`

Can you manually import that image into the headnode's zpool? From the headnode GZ run: `imgadm import d8c747ca-ebde-11e5-aca6-bf9f0954e211`

**Comment by benjamin-bergia** [comment]
After importing the image using imgadm, everything worked fine. Thank you very much for your help.
